~ variables are declared with the 'let' keyword ~
let x = 1;
print('the value of x is', @red, x);

~ types of arithmetic operations ~
print('x * 13 =', @orange, x*13);
print('24 / 2 =', @yellow, 24/2);
print('24 / 2 + 2 =', @lime, 24/2+2);
print('24 + 2 / 2 =', @cyan, 24+2/2);
print('20 - 10 =', @blue, 20 - 10);
print('18 >= 6 =', @purple, 19 >= 6);
print('"hello " .. "world" =', @magenta, "hello ".."world");